Remove dead links and update docs
IBM/detect-secrets-stream pull request #15
Opened 2021-06-03 19:36 UTC by victoria-miltcheva

This PR transfers over some docs from the internal detect-secrets which we should be public knowledge. If I missed any docs please, let me know!

It also cleans up all dead / internal links.

2021-06-03 20:11 UTC, justineyster reviewed
Two things so far...

2021-06-03 20:11 UTC, justineyster commented on docs/about-detect-secrets.md
> +This does _not_ affect the current Github app in any way. Both services follow different flows and can be run concurrently without any issues.
The app is internal and has been sunset. We can remove this section.

2021-06-03 20:11 UTC, justineyster commented on docs/developer-tool-faq.md
> +# FAQs (Detect Secrets Suite - Developer tool)
Why move the dev tool docs into the server side tool repo? 🤔

2021-06-03 20:21 UTC, victoria-miltcheva commented on docs/developer-tool-faq.md
> +# FAQs (Detect Secrets Suite - Developer tool)
They were linked to from this repo's README, but it may make more sense to put them in https://github.com/IBM/detect-secrets. I'm going to go ahead and remove them from here and create a separate PR for that.

2021-06-03 20:27 UTC, victoria-miltcheva commented on docs/about-detect-secrets.md
> +This does _not_ affect the current Github app in any way. Both services follow different flows and can be run concurrently without any issues.
https://github.com/IBM/detect-secrets-stream/pull/15/commits/654bc25b26de0bc4f65030cfbe5d8fc1cea837b3

2021-06-03 20:33 UTC, justineyster commented on docs/developer-tool-faq.md
> +# FAQs (Detect Secrets Suite - Developer tool)
https://github.com/IBM/detect-secrets is a direct clone of the internal whitewater-detect-secrets repo. We don't push to it directly. If you want to move wiki material into source code, I'd put it in the internal one first! The public version will be updated to match automatically on deployment.

2021-06-03 20:36 UTC, victoria-miltcheva commented on docs/developer-tool-faq.md
> +# FAQs (Detect Secrets Suite - Developer tool)
https://github.com/IBM/detect-secrets/pull/8

2021-06-03 20:54 UTC, victoria-miltcheva commented on docs/developer-tool-faq.md
> +# FAQs (Detect Secrets Suite - Developer tool)
Gotcha, I wasn't aware of that. I'll go ahead and put it in the internal one. I may have created a PR against https://github.com/IBM/detect-secrets but I'll go ahead and close that 😅 . Didn't see your comment until now.

2021-06-08 03:58 UTC, justineyster reviewed
A few suggestions!

Two more kind of general thoughts: there's a lot of use of the words "our", "we", etc. in these docs. I wonder if we should avoid those words and just talk about the tool's behavior instead of our own design decisions, now that DSS will not be managed by just our company/team. i.e. "detect-secrets-stream does xyz" instead of "we do xyz".

Secondly, the intended audience for `docs/about-detect-secrets.md` is primarily GHE end users whereas for the rest of them it's the developers managing the tool. You could maybe try to make that more clear or call that out now that these docs are living in the same place.

2021-06-08 03:58 UTC, justineyster commented on README.md
> +The live secrets are reported to the Vulnerability Management team (VMT). Currently, the reporting is through csv file uploaded in shared box folder. We are about to make a change to report through a
This line can be removed or edited to be non-IBM-specific.

2021-06-08 03:58 UTC, justineyster commented on README.md
> +The live secrets are reported to the Vulnerability Management team (VMT). Currently, the reporting is through csv file uploaded in shared box folder. We are about to make a change to report through a
Also the read-only DB table is implemented now.

2021-06-08 03:58 UTC, justineyster commented on docs/about-detect-secrets.md
> +- Shallow scan: scan all (non-binary) files at current commit. This is the default behavior for detect-secrets-suite developer tool.
You could link to the public GitHub dev tool here.

2021-06-08 03:58 UTC, justineyster commented on docs/about-detect-secrets.md
> +detect-secrets-suite server runs delta (diff) scan for each commit included in the git push. If many commits included, it will scan up to 250 commits per branch. For example, if your push only contai
I believe the 250 commit limit is inaccurate based on [this line of code](https://github.com/IBM/detect-secrets-stream/blob/394cdd73c991d4627e8b14dd3d6e2597634f1067/detect_secrets_stream/gd_ingest/api.py#L61). 250 is in fact the default value for max commits as [defined in the class's init function](https://github.com/IBM/detect-secrets-stream/blob/394cdd73c991d4627e8b14dd3d6e2597634f1067/detect_secrets_stream/gd_ingest/commitparser.py#L13), but we're overriding it with 25 when the class is initialized. We may have updated the functionality since originally writing the docs.

2021-06-08 21:19 UTC, victoria-miltcheva commented on README.md
> +The live secrets are reported to the Vulnerability Management team (VMT). Currently, the reporting is through csv file uploaded in shared box folder. We are about to make a change to report through a
https://github.com/IBM/detect-secrets-stream/pull/15/commits/6de0130a83c72755628551ed549d3a363ca49f86

2021-06-08 21:25 UTC, victoria-miltcheva commented on docs/about-detect-secrets.md
> +detect-secrets-suite server runs delta (diff) scan for each commit included in the git push. If many commits included, it will scan up to 250 commits per branch. For example, if your push only contai
https://github.com/IBM/detect-secrets-stream/pull/15/commits/a19404d1aaf7642945136a424920519159e8a433

2021-06-08 21:28 UTC, victoria-miltcheva commented
>there's a lot of use of the words "our", "we", etc. in these docs. I wonder if we should avoid those words and just talk about the tool's behavior instead of our own design decisions, now that DSS will not be managed by just our company/team. i.e. "detect-secrets-stream does xyz" instead of "we do xyz".

@justineyster that's a good observation, it makes sense to refer to the tool itself rather than "we". I'll go ahead and make this change. I'll also noticed some grammar errors in the doc, so I'll fix those as well.

>Secondly, the intended audience for docs/about-detect-secrets.md is primarily GHE end users whereas for the rest of them it's the developers managing the tool. You could maybe try to make the former more clear now that these docs are living in the same place.

Will do.

2021-06-08 22:47 UTC, victoria-miltcheva commented
@justineyster I appreciate your feedback, and I wanted to let you know that this PR is ready for another review. These are the changes I've made:
- Fixed grammar errors
- Renamed `about-detect-secrets.md` to `detect-secrets-suite-faq.md`
- Noted the intended audience for the Detect Secrets Suite FAQ
- Removed references to "we", "our", etc.

2021-06-09 02:53 UTC, justineyster approved these changes
One last thing. Approving so you can feel free to merge it after addressing! Thanks for working on this! 😄

2021-06-09 02:53 UTC, justineyster commented on detect_secrets_stream/gd_revoker/usage.md
> +`curl -X POST https://gd-revoker.<host_suffix>./api/v1/token/<uuid>/verify`
The period after `<host_suffix>` should be removed.

2021-06-09 12:48 UTC, killuazhu requested changes
@victoria-miltcheva thanks for making the doc updates! It looks quite nice, I've added some wording suggestions.

2021-06-09 12:48 UTC, killuazhu commented on README.md
> +Detect Secrets Stream is a server tool which ingests metadata of all (public repositories by default, private repositories are opt-in only) git pushes on your company's GitHub server. For each push,
```suggestion
Detect Secrets Stream is a server tool which ingests metadata of all (public repositories by default, private repositories are opt-in only) git pushes on your company's GitHub Enterprise server. For each push, it [scans](./docs/detect-secrets-suite-faq.md#what-file-content-do-you-scan) the push contents for secrets. Once found and verified, secrets metadata will be stored in a database, and the raw secret will be stored in Vault.
```

2021-06-09 12:48 UTC, killuazhu commented on README.md
> +Running the utility requires several environment variables. You will first need to unlock secrets using `git-crypt`, then export the required environment variables. An example environment variable fi
```suggestion
Running the utility requires several environment variables. An example environment variable file (`.env.example`) has been provided.
```

2021-06-09 12:48 UTC, killuazhu commented on README.md
>  cp .env.example .env.prod
There is a better way to expose env var with [`direnv`](https://direnv.net/)   That can be added in future PR.

2021-06-09 12:48 UTC, killuazhu commented on detect_secrets_stream/gd_revoker/usage.md
> +`curl -X POST https://gd-revoker.<host_suffix>./api/v1/token/<uuid>/verify`
Avoid dictating the revoker endpoint needs to start with `gd-revoker`

```suggestion
`curl -X POST https://<server>/api/v1/token/<uuid>/verify`
```

2021-06-09 12:48 UTC, killuazhu commented on detect_secrets_stream/gd_revoker/usage.md
> +`curl -X POST https://gd-revoker.<host_suffix>/api/v1/token/<uuid>/revoke`
Same as above, avoid dictating the revoker endpoint needs to start with `gd-revoker`

```suggestion
`curl -X POST https://<server>/api/v1/token/<uuid>/revoke`
```

2021-06-09 12:48 UTC, killuazhu commented on detect_secrets_stream/secret_corpus_db/gd_db_tools.py
> +        # Credentials from the PostgreSQL database
Good catch!

2021-06-09 12:48 UTC, killuazhu commented on docs/detect-secrets-suite-faq.md
> +For your own CI/CD issues, please refer to your GitHub Organization owner.
Let's take out this one, does not seem too relevant.

2021-06-09 12:48 UTC, killuazhu commented on docs/detect-secrets-suite-faq.md
> +This documentation is intended for GitHub Enterprise end users. The rest of the documentation in this repository is intended for developers managing the Detect Secrets Stream tool.
```suggestion
# Detect Secrets Stream FAQ

This documentation is intended for GitHub Enterprise end users.
```

2021-06-09 13:00 UTC, victoria-miltcheva commented on detect_secrets_stream/secret_corpus_db/gd_db_tools.py
> +        # Credentials from the PostgreSQL database
Thanks!

2021-06-09 13:04 UTC, victoria-miltcheva commented on docs/detect-secrets-suite-faq.md
> +For your own CI/CD issues, please refer to your GitHub Organization owner.
https://github.com/IBM/detect-secrets-stream/pull/15/commits/db95d2ecee4ece50dc5b922b4774d936c5e6132a

2021-06-09 13:04 UTC, victoria-miltcheva commented on detect_secrets_stream/gd_revoker/usage.md
> +`curl -X POST https://gd-revoker.<host_suffix>./api/v1/token/<uuid>/verify`
https://github.com/IBM/detect-secrets-stream/pull/15/commits/db95d2ecee4ece50dc5b922b4774d936c5e6132a

2021-06-09 13:25 UTC, killuazhu approved these changes
📝 🎉

2021-06-09 15:12 UTC, merged