Site admin faq
IBM/detect-secrets-stream pull request #20
Opened 2021-06-22 19:52 UTC by victoria-miltcheva

**Description of changes**
- `docs/admin-tool-faq.md`: Duplicated + revised docs for DSS admins (from detect-secrets-discuss: [Admin] DSS Admin FAQ)
- `docs/detect-secrets-stream-faq.md`: Simplifies headings and regenerates table of contents
-  `docs/admin-tool-faq.md`: Not sure why the PR is showing that this is a new file when the exact file already exists in `main`? Ignore this, I guess.

2021-06-22 20:29 UTC, justineyster commented on docs/ghe-site-admin-faq.md
> +- check `Administrators can enable and disable this hook`
We enable the pre-receive hook in some kind of test/debug mode that is always non-blocking, allowing the scan to complete asynchronously. We may need a site admin to help us figure out exactly what the option is called, but that's definitely worth noting here!

2021-06-22 20:41 UTC, justineyster commented on docs/ghe-site-admin-faq.md
> +- check `Administrators can enable and disable this hook`
The more I look into this the more I think this documentation is likely out of date with how we actually have it configured. I think we probably uncheck 'Use the exit-status to accept or reject pushes' which makes the hook always non-blocking. And we may uncheck 'Administrators can enable and disable this hook'. Again though, need confirmation from a site admin. But I found this screenshot in [GitHub's documentation](https://docs.github.com/en/enterprise-server@3.1/admin/policies/enforcing-policy-with-pre-receive-hooks/managing-pre-receive-hooks-on-the-github-enterprise-server-appliance) that makes me believe that unchecking the first option results in the test/debug mode I was referring to in my first comment.
![hook-name](https://user-images.githubusercontent.com/6627492/122996259-a902c780-d378-11eb-82ee-a01e62e8844b.png)

2021-06-28 13:44 UTC, victoria-miltcheva commented on docs/ghe-site-admin-faq.md
> +- check `Administrators can enable and disable this hook`
Note: John Edwards will verify this. Also:
>Summary - 5 seconds still applies, to the Appliance for kyndryl also.  Also we use the hook in test mode so it doesn't stop the commit with non-zero RC.

2021-06-28 18:31 UTC, justineyster commented on docs/ghe-site-admin-faq.md
> +- check `Administrators can enable and disable this hook`
@victoria-miltcheva Were you able to confirm what settings we use?

2021-06-28 19:23 UTC, killuazhu requested changes
Thanks for making the change, I've added some clarifications for pre-receive hook setup.

2021-06-28 20:43 UTC, victoria-miltcheva commented on docs/ghe-site-admin-faq.md
> +- check `Administrators can enable and disable this hook`
Addressed! https://github.com/IBM/detect-secrets-stream/pull/20/commits/ae8c667d975d1fc7f8531e35e2be334b42699b18

2021-06-28 21:12 UTC, killuazhu approved these changes
LGTM

2021-06-28 21:33 UTC, merged