docs(app-patch-management): create
IBM/detect-secrets-stream pull request #21
Opened 2021-06-27 19:00 UTC by victoria-miltcheva

Duplicates docs for https://github.ibm.com/git-defenders/detect-secrets-discuss/wiki/%5BAdmin%5D-App-Patch-Management

2021-06-27 19:12 UTC, victoria-miltcheva commented on docs/app-patch-management-faq.md
> +- `detect-secrets-updater`: runs daily to scan for vulnerabilities in published Docker image with `latest` and latest version tag.
I wasn't sure if we were planning on setting up renovate bot for this repo or possibly Dependabot. I also wasn't sure if we were planning on moving `detect-secrets-updater` over as well. I'll keep these in the docs if we're going to include these, otherwise, I'll remove them.

2021-06-28 18:36 UTC, justineyster reviewed
Two quick questions.

2021-06-28 18:36 UTC, justineyster commented on docs/app-patch-management-faq.md
> +- `renovate bot`, `git-defender version`: runs a daily scan for app-level vulnerabilities based on Pipenv lockfile and Dockerfiles. It automatically opens PRs for vulnerability resolution.
What is `git-defender version`?

2021-06-28 18:36 UTC, justineyster commented on docs/app-patch-management-faq.md
> +| server: dss images                                              | **detection**: trivy + issue<br/> **fix**: manual                         | **detection**: issue<br/>**fix**: renovate bot
`Detection: issue` means an issue is automatically opened, I assume? Doesn't renovate bot actually open a PR?

2021-06-28 19:26 UTC, killuazhu requested changes
Let's keep this one internal. The patching process specific to the IBM GHE dev tool.

2021-06-28 19:40 UTC, victoria-miltcheva commented on docs/app-patch-management-faq.md
> +- `renovate bot`, `git-defender version`: runs a daily scan for app-level vulnerabilities based on Pipenv lockfile and Dockerfiles. It automatically opens PRs for vulnerability resolution.
That was referring to the renovate-bot repo under the git-defenders org, I've removed this: https://github.com/IBM/detect-secrets-stream/pull/21/commits/f6f389c0e150a46e82317d2a2f3b805863a7b679

2021-06-28 19:44 UTC, victoria-miltcheva commented
@killuazhu sure! Closing this PR.

2021-06-28 19:44 UTC, closed without merging